### ISSUE TITLE
public final static fields leak into the meta-model

### ISSUE THREAD

**Issue by veselov** [datanucleus/datanucleus-jpa-query#3]
I believe any static field in the entities should be ignored, but the compiler does include them into the metamodel. I only discovered it because I have type parameters, and the compilation choked on them, as they are copied from the source class, without being resolved.

I've posted the test case at git@github.com:veselov/test-jpa.git
Running `mvn test` fails.

Workaround is to mark the field as `@Transient`

**Comment by andyjefferson** [comment]
Your github project has no persistent field that is static. Also "jpa-query" would need the "datanucleus-jpa-query" jar to be in the build so that it can create the metamodel classes, so perhaps you are pointing this to something incorrect?

**Comment by veselov** [comment]
Commit fail on my part, didn't add all the diffs into it. Updated the test case, but you've already fixed it :+1: :)
