### ISSUE TITLE
@Basic @Lob Serializable entity field results in errornous metamodel

### ISSUE THREAD

**Issue by krichter722** [datanucleus/datanucleus-jpa-query#5]
A field

    @Basic
    @Lob
    private AbstractUnit<?> priceUnit = (AbstractUnit<?>)AbstractUnit.ONE;

results in generation of

    public static volatile SingularAttribute<MyEntity, tec.uom.se.AbstractUnit<Q>> priceUnit;

which uses an unspecified generic parameter `Q` and thus causes invalid Java code using

```
    <plugin>
        <groupId>org.bsc.maven</groupId>
        <artifactId>maven-processor-plugin</artifactId>
        <version>3.3.2</version>
        <executions>
            <execution>
              <id>datanucleus-metamodel</id>
              <goals>
                    <goal>process</goal>
              </goals>
              <phase>generate-sources</phase>
              <configuration>
                <processors>
                    <processor>org.datanucleus.jpa.query.JPACriteriaProcessor</processor>
                </processors>
              </configuration>
            </execution>
        </executions>
        <dependencies>
            <dependency>        
                <groupId>org.datanucleus</groupId>
                <artifactId>datanucleus-jpa-query</artifactId>
                <version>5.0.4-SNAPSHOT</version>
            </dependency>
        </dependencies>
    </plugin>
```
A SSCCE is https://gitlab.com/krichter/datanucleus-metamodel-abstrakt-unit-field.

experienced with 5.0.3 and 5.0.4-SNAPSHOT and DataNucleus 5.1.4 including the fix of #4 

The similarity of #4 and this issue point to missing unit test cases or low test coverage. I'll try to get a build script running for a CI service like Travis or GitLab CI which integrates with a coverage measure platform and suggest a PR. In case that fails, you should consider it.

**Comment by krichter722** [comment]
Did you verify the fix with the SSCCE? I'm still getting the same error with datanucleus-jpa-query-5.0.3-3-gad42efe.

**Comment by andyjefferson** [comment]
I verified it with a test I generated, with a field of a non-Entity type that has generics. Because your link says "The repository for this project is empty" (not committed?). But then this plugin is all of 2 classes, so it really ought to be simple to find where the problem is for your case (if it is different), and provide a fix.

**Comment by krichter722** [comment]
> "The repository for this project is empty" (not committed?)

Yup. Now it's available.

> But then this plugin is all of 2 classes, so it really ought to be simple to find where the problem is for your case (if it is different), and provide a fix.

Looking forward to it :)

**Comment by andyjefferson** [comment]
Yes, the second comment is ... for you.

**Comment by krichter722** [comment]
It's almost infinitely more complex for me to fix than for you. It doesn't make sense for me to dive into a new project to fix a bug that blocks an important use case, no matter how small the number of classes is.

**Comment by andyjefferson** [comment]
Sorry, but I do not have loads of free time. The point is simple, I fixed what I found, and I spent my available time on it. This is important to you, not me. 

The class in question is
https://github.com/datanucleus/datanucleus-jpa-query/blob/ad42efe3921d5c2f319467374772f77b0c0d9106/src/main/java/org/datanucleus/jpa/query/JPACriteriaProcessor.java#L234
so you work your way down for the particular member (field) that is the problem in your class. It is simply going to append the name of the field type. Your "self-contained test" is not that ... missing the related type. 

As already said, I took the time to simulate that in DN tests, https://github.com/datanucleus/tests/blob/master/jpa/criteria/src/java/org/datanucleus/samples/jpa/query/QueryTypes.java#L44
